# Generated by Django 3.2.13 on 2022-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_video_id'),
        ('playlists', '0004_alter_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlist_item', to='videos.Video'),
        ),
    ]
