# Generated by Django 3.2.13 on 2022-06-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_alter_playlist_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
