# Generated by Django 3.2.13 on 2022-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20220621_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
